create table Courses (
                         id bigint generated by default as identity primary key,
                         name varchar(100) not null,
                         total_seats int not null,
                         occupied_seats int not null,
                         start_date timestamp not null,
                         end_date timestamp not null
);

create table Students (
                          id bigint generated by default as identity primary key,
                          name varchar(100) not null
);

create table Enrollments
(
    id bigint generated by default as identity primary key,
    course_id bigint references Courses(id) on delete cascade,
    student_id bigint references Students(id) on delete cascade
);

create unique index idx_student_course on Enrollments(student_id, course_id);